# Generated by Django 5.1.4 on 2024-12-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='Name')),
                ('item_type', models.CharField(max_length=30, verbose_name='Type')),
                ('size', models.CharField(max_length=5, verbose_name='Size')),
            ],
        ),
    ]
