# Generated by Django 5.1.4 on 2024-12-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('add_date', models.DateTimeField(verbose_name='Time Added')),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3, verbose_name='Size')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('price', models.FloatField(verbose_name='Price')),
                ('available_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount in stock')),
                ('sold_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount sold')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Time added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.itemspecification')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=45, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('payment_method', models.CharField(choices=[('VNPayQR', 'VNPayQR'), ('MoMo', 'MoMo'), ('Credit Card', 'Credit Card'), ('ATM Card', 'ATM Card'), ('Debit Card', 'Debit Card')], max_length=20, verbose_name='Payment method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Rating')),
                ('review', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Review')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemspecification',
            constraint=models.UniqueConstraint(fields=('item', 'size', 'color'), name='primary_key'),
        ),
        migrations.AddConstraint(
            model_name='itemspecification',
            constraint=models.CheckConstraint(condition=models.Q(('available_qty__gte', 0)), name='available_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='itemspecification',
            constraint=models.CheckConstraint(condition=models.Q(('sold_qty__gte', 0)), name='sold_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='itemspecification',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='user_and_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__lte', 5)), name='rating_between_0_and_5'),
        ),
    ]
