# Generated by Django 5.1.4 on 2024-12-21 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Added'),
            preserve_default=False,
        ),
    ]
