# Generated by Django 5.1.4 on 2024-12-26 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='add_time',
        ),
        migrations.AddField(
            model_name='purchase',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of purchase'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('status', models.CharField(choices=[('Not Delivered', 'Not Delivered'), ('Delivering', 'Delivering'), ('Received', 'Received'), ('Returned', 'Returned')], max_length=20, verbose_name='Status')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.itemspecification')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.purchase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('purchase', 'item'), name='purchase_and_item_unique')],
            },
        ),
    ]
