# Generated by Django 5.1.4 on 2024-12-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='home.type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AvailableSizesAndColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3, verbose_name='Size')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('price', models.FloatField(verbose_name='Price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'size', 'color'), name='primary_key')],
            },
        ),
    ]
