# Generated by Django 5.1.4 on 2024-12-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_type_rename_item_id_item_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSizesAndColors',
            new_name='AvailableSizeAndColor',
        ),
    ]
