# Generated by Django 5.1.4 on 2024-12-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_availablesizesandcolors_availablesizeandcolor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='category',
        ),
    ]
