# Generated by Django 5.1.4 on 2024-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_type_category_rename_type_item_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSizeAndColor',
            new_name='Specification',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
        ),
    ]
