# Generated by Django 5.1.4 on 2024-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_availablesizeandcolor_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Description'),
        ),
    ]
