# Generated by Django 5.1.4 on 2024-12-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Description'),
        ),
    ]
