# Generated by Django 5.1.4 on 2024-12-24 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Rating')),
                ('review', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Review')),
            ],
        ),
        migrations.AddField(
            model_name='specification',
            name='available_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount in stock'),
        ),
        migrations.AddField(
            model_name='specification',
            name='sold_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount sold'),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 7, 50, 27, 239083), verbose_name='Time Added'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.CheckConstraint(condition=models.Q(('available_count__gte', 0)), name='available_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.CheckConstraint(condition=models.Q(('sold_count__gte', 0)), name='sold_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_nonnegative'),
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__lte', 5), ('rating__gte', 0)), name='rating_between_0_and_5'),
        ),
    ]
