# Generated by Django 5.1.4 on 2024-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_item_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(verbose_name='Time Added'),
        ),
    ]
