# Generated by Django 5.1.4 on 2024-12-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_item_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Time added')),
            ],
        ),
        migrations.RenameModel(
            old_name='Specification',
            new_name='ItemSpecification',
        ),
        migrations.RemoveConstraint(
            model_name='itemspecification',
            name='available_count_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='itemspecification',
            name='sold_count_nonnegative',
        ),
        migrations.RenameField(
            model_name='itemspecification',
            old_name='available_count',
            new_name='available_qty',
        ),
        migrations.RenameField(
            model_name='itemspecification',
            old_name='sold_count',
            new_name='sold_qty',
        ),
        migrations.AddConstraint(
            model_name='itemspecification',
            constraint=models.CheckConstraint(condition=models.Q(('available_qty__gte', 0)), name='available_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='itemspecification',
            constraint=models.CheckConstraint(condition=models.Q(('sold_qty__gte', 0)), name='sold_qty_nonnegative'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.itemspecification'),
        ),
    ]
